main.py
from flask import Flask
from routes.home import home_route
from routes.client import client_route
#inicializaçao
app= Flask(__name__)

#rotas
app.register_blueprint(home_route)
app.register_blueprint(client_route, url_prefix='/clientes')

#execuçao
app.run(debug=True)

routes/client.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES

client_route= Blueprint('client', __name__)

"""""
rota de clientes

-/clientes/ (get)listar clientes
-/clientes/ (post) inserir clientes
-/çlientes/new (get) form para criar new client
-/clientes/id (get)- obter dados de um cliente por id
-/clientes/id/edit (get) renderizar um formulario para editar os dados
-/clientes/id/update (put) atualiza os dados
/clientes/id/delete (delete) deleta um cliente
"""
@client_route.route('/')
def lista_client():
    return render_template('listaclientes.html', clientes=CLIENTES)
    
@client_route.route('/', methods=['POST'])
def inserir_client():
    data = request.json
    print(data)
    novo_usuario = {
        "id": len(CLIENTES) +1,
        "nome": data['Nome'],
        "email": data['Email']
    }
    CLIENTES.append(novo_usuario)
    return render_template('item_cliente.html', cliente= novo_usuario)

@client_route.route('/new')
def for_new_client():
    return render_template('form_client.html')

@client_route.route('/<int:client_id>' )
def detalhe_client(client_id):
    return render_template('detalhe_client.html')

@client_route.route('/<int:client_id>/edit')
def form_edit_client(client_id):
    cliente= None
    for c in CLIENTES:
        if c["id"]==client_id:
            cliente=c
    return render_template('form_client.html', cliente= cliente)

@client_route.route('/<int:client_id>/update', methods=['PUT'])
def update_client(client_id):
    pass

@client_route.route('/<int:client_id>/delete', methods=['DELETE'])
def delete_client(client_id):
    global CLIENTES
    CLIENTES = [ c for c in CLIENTES if c["id"] !=client_id  ]
    return {"retorno":"true"}

routes/home.py
from flask import Blueprint, render_template

home_route= Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form_client.html
<form class="c-form" action="{{ url_for('client.inserir_client') }}" method="POST" c-append="#lista-clientes">
  <div class="mb-3">
    <label class="form-label">Nome</label>
    <input type="text" class="form-control" name="Nome" />
  </div>
  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control" name="Email" />
  </div>

  <button type="submit" class="btn btn-primary">adicionar cliente</button>
</form>

templates/index.html
    <!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Bootstrap demo</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
        <link rel="stylesheet" href="static/css/app.css" />
        <!-- e possivel utilizar o url for neste link -->
    </head>
    <body>
        <div class="container">
        <h1 class="text-center">gestao de clientes</h1>
        <div id="form-client" c-container="{{ url_for('client.for_new_client') }}"></div>
        <hr>
        <h2>lista de clientes</h2>
        <div c-container="{{ url_for('client.lista_client') }}"></div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
    </body>
    </html>

templates/item_cliente.html
<tr>
  <th scope="row">{{ cliente.id }}</th>
  <td>{{ cliente.nome }}</td>
  <td>{{ cliente.email }}</td>
  <td>
    <button class="btn btn-primary" 
    c-get="{{ url_for('client.form_edit_client', client_id=cliente.id) }}" c-target="#form-client">
    editar</button>
    <button class="btn btn-danger"
      c-delete="{{ url_for('client.delete_client', client_id=cliente.id) }}" 
      c-remove-closest="tr">deletar</button>
  </td>
</tr>

templates/listaclientes.html
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Açoes</th>
    </tr>
    </thead>
    <tbody id="lista-clientes">
        {%for cliente in clientes%}
            {% include 'item_cliente.html' %}
        
        {%endfor%}
    </tbody>
</table>